# Site settings
title: Curso de Python para principiantes
email:
description: > # this means to ignore newlines until "baseurl:"
  Página web del curso de Python para principiantes 2017. Este curso tendrá
  lugar en la Universidad Carlos III de Madrid del 13 al 15 de diciembre.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
