# Site settings
title: Curso de Python para principiantes
email:
description: > # this means to ignore newlines until "baseurl:"
  Página web del curso de Python para principiantes Python4Beginners. Este curso tendrá
  lugar en la Universidad Carlos III de Madrid del 13 al 15 de diciembre.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: "Python4Beginners"
email: "info@pyscience.es"
facebook_username: "py4beginners"
twitter_username: "py4beginners"
github_username:
address:
  - line: "Universidad Carlos III de Madrid: Campus de Leganés, Av. de la Universidad, 30, 28911 Leganés, Madrid"
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key: "AIzaSyCWH4BM4r1IlaGLHfSw0xq92QCoZxy4sQY"

# Build settings
markdown: kramdown
